[tool.poetry]
name = "repl_python3_python-shell-reverse"
version = "0.1.0"
description = ""
authors = ["TeuzimMG <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
psutil = "^5.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
